### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by boaks**
Bugfixes:
- some (potential) memory leaks
- initial observe request
- payload size in test-client and -server
- tlv decoding values with larger lengths (e.g. between 128 and 255)

### CODE REVIEW

**Comment by boaks** [comment]
"I can see the memory leak but I don't get your fix. Why call coap_set_payload() twice ?"
Your right, one is enough :-). 

"Why not test the return of handle_observe_request() and act accordingly ?"
Do you use a "memory sanitizer" tool to detect leaks?
As far as my tools signals, "object_read" allocates the buffer. If you don't set this buffer as response, the pointer gets lost and this will cause a "memory leak".
So, if the server request an observation, the buffer gets allocated. If then handle_observe_request() returns an error (e.g. see above COAP_401_UNAUTHORIZED, when update registration is pending), the buffer is not set as payload and therefore gets lost as memory leak.

**Comment by boaks** [comment]
"From a security point-of-view, it is better to discard requests from server in Update Pending State."

I didn't find something about that special security problem during update registration in the LwM2M specification. I even didn't find a hint for special LwM2M-client side processing during that period in the LwM2M specification. So could you help me out, pointing me to information, which describes this risc and the special processing rules?

Be aware, that the "update registration" may cross the "observe" so the server has no chance to detect the situation ahead. And it would get rather complex, to process the COAP_401_UNAUTHORIZED depending on a pending update registration. 
(I guess, currently no server will handle this properly.)

**Comment by dnav** [comment]
Regarding the handle_observe_request() memory leak:
if you set the buffer as the payload, it will be returned in the response containing the 4.01 code, creating a security hole. My idea was to change the code to:
 result = object_read(contextP, uriP, &buffer, &length);
 if (result == COAP_205_CONTENT)
 {
       if (IS_OPTION(message, COAP_OPTION_OBSERVE))
       {
            result = handle_observe_request(contextP, uriP, fromSessionH, message, response);
       }
       if (result == COAP_205_CONTENT)
       {
            coap_set_payload(response, buffer, length);
            // lwm2m_handle_packet will free buffer
        }
+      else
+      {
+            lwm2m_free(buffer);
+      }
  }

**Comment by boaks** [comment]
"if you set the buffer as the payload, it will be returned in the response containing the 4.01 code, creating a security hole."

Very good point! So free it explicitly is the better choice.

**Comment by dnav** [comment]
About the observation while updating the registration:
There are no advice on how to handle requests during the update in the TS. I was just expressing my concern. But upon close examination, I actually can't see how it can hurt. So let's go with your change.

**Comment by boaks** [comment]
"There is currently a mismatch between CoAP Observe spec and LWM2M TS on this. Let's follow LWM2M TS until this is sorted out. But note 2.04 is a valid code for a notify message."

"OMA-DM-LightweightM2M-2015-0007R01-CR_Erratas_Complement" mentions the 2.04 as error and fixed it to 2.05 (8.2.5, page 3). Don't know, why the TS wasn't updated also. But it's also Ok to wait for a TS update.

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20150228-D, 8.2.5, page 65.
Now the 2.05 is in the specification (at least n the draft).

**Comment by dnav** [comment]
I saw this.
Please change the fix for the memory leak in handle_observe_request() and I'll merge your PR.

**Comment by boaks** [comment]
Changed.

**Comment by dnav** [comment]
Could you rebase to eclipse:master ? There is a small conflict in lwm2mclient.c.
I moved some curly braces. Sorry for that.

**Comment by boaks** [comment]
Rebased.

**Pull request merged**
