### PR TITLE
Unified block transfer and non-block transfer callbacks.

### PR DESCRIPTION
**Pull request by mlasch**
This is implementing changes mentioned in #537.

Signed-off-by: Marc Lasch <marc.lasch@husqvarnagroup.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
@mlasch thx you for the contribution :pray:

To be able to accept you contribution we need you to [sign an ECA](https://www.eclipse.org/legal/ECA.php) : eclipse process :grimacing:.

See for more details : https://github.com/eclipse/leshan/wiki/How-to-contribute#legal-stuff-  (We need this kind of page for wakaama too)

**Comment by sbertin-telular** [comment]
@sbernard31 do you mean something like https://github.com/eclipse/wakaama/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by mlasch** [comment]
@sbernard31 Thanks for your reply, too many different email addresses... should be ok now.

**Comment by sbernard31** [comment]
> @sbernard31 do you mean something like https://github.com/eclipse/wakaama/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement

Exactly :sweat_smile:

**Review by qleisan — APPROVED** [review]
Much cleaner. LGTM

**Comment by sbernard31** [comment]
Integrated in master (commit 66f8c432e3596dc8dee54afc6a33f0801c3af439)

Thx you very much @mlasch for the contribution :pray:

**Pull request closed without merging**
