### PR TITLE
Support Bootstrap-Read and Bootstrap-Discover

### PR DESCRIPTION
**Pull request by sbertin-telular**
Signed-off-by: Scott Bertin <sbertin@telular.com>

### CODE REVIEW

**Comment by qleisan** [comment]
Starting to review (and read up on spec....). Expect to be done later today

**Review by qleisan — APPROVED** [review]
Code-wise I have no objections but I struggle a bit with the bigger picture (how this is used/triggered). I believe this code is already tested and "in production". (Right?) I'll approve so it can be merged but will continue to read up and do hands on tests

**Comment by qleisan** [comment]
[210305_PR549_test1.pcapng.zip](https://github.com/eclipse/wakaama/files/6089303/210305_PR549_test1.pcapng.zip)
[210305_PR549_test2.pcapng.zip](https://github.com/eclipse/wakaama/files/6089305/210305_PR549_test2.pcapng.zip)

Found blocktransfer related issue while testing Bootstrap-Discover
modified `bootstrap_server.ini` as follows:
```
# For any client, we delete all server accounts and
# provision the Leshan server info
[Endpoint]
Delete=/0
Delete=/1
Server=1
Discover=/
```
launched example bootstrap server, server and client
```
./build-bootstrap/bootstrap_server -f examples/bootstrap_server/bootstrap_server.ini -4
./build-server/lwm2mserver -4
./build-client/lwm2mclient -4 -b -n bepa2
```

With `REST_MAX_CHUNK_SIZE` set to 128 (current setting) the result was according to **test2** - _ERROR_
With `REST_MAX_CHUNK_SIZE` set to 512 (modified setting) the result was according to **test1** - _OK_

also it would be helpful for the end user with some updated comments in the .ini file about the new command(s)

**Comment by sbernard31** [comment]
About **210305_PR549_test2.pcapng.zip** this looks like #536, as Wakaama answers to a response with a response (See MID 55386).

I see that Bootstrap server try several time to send the discover request ? does it go in an infinite loop or the retry we see are just retransmission ?

**Comment by sbertin-telular** [comment]
I'm not using these features in production. This was to make Wakaama more feature complete.

I'll update MAX_PACKET_SIZE  and add some comments to the .ini file.

**Review by qleisan — APPROVED** [review]

**Comment by sbertin-telular** [comment]
Squashed

**Comment by sbernard31** [comment]
@qleisan, @tuve about https://github.com/eclipse/wakaama/pull/549#issuecomment-791279205 we need maybe a dedicated issue to track this ?

**Comment by qleisan** [comment]
created #551

**Pull request merged**
