### PR TITLE
Support the preferred content format for Bootstrap-Request

### PR DESCRIPTION
**Pull request by sbertin-telular**
Signed-off-by: Scott Bertin <sbertin@telular.com>

### CODE REVIEW

**Comment by qleisan** [comment]
(Started to review. Will resume later today)

**Review by qleisan — APPROVED** [review]

**Review by tuve — APPROVED** [review]
I agree with @qleisan that the README should be updated as well. But codewise i think this is fine.

**Comment by sbertin-telular** [comment]
Thanks for the review. This is the problem integrating year+ old changes with new changes, something always gets missed. I'll update.

**Comment by sbertin-telular** [comment]
I've updated the README.md and rebased.

**Review by qleisan — APPROVED** [review]

**Pull request merged**
