### PR TITLE
Fix memory leak if the client fails to register with the server

### PR DESCRIPTION
**Pull request by parmi93**
Fix memory leak when client register to the server
See: https://github.com/eclipse/wakaama/issues/693

### CODE REVIEW

**Comment by rettichschnidi** [comment]
Thanks for your PR. Before we can integrate, please sign the [ECA](https://accounts.eclipse.org/user/eca)..

**Comment by rettichschnidi** [comment]
It is not obvious to me how exactly this resolves a memory leak. Will try to have a closer look and read up on #693 latest by Friday 2023-05-12.

**Comment by rettichschnidi** [comment]
Sorry for not giving feedback earlier. Checking this (long) weekend.

Meanwhile, for the CI checks to pass, please add a body to your commit, explaining a bit what exactly the commit does.

**Review by parmi93 — COMMENTED** [review]
test

**Comment by parmi93** [comment]
How can I add the body to my commit? I can't find the option anywhere

**Comment by rettichschnidi** [comment]
@parmi93 I reopened this issue because there is no need to create a new Pull Request (PR) to improve an existing commit.

You need to edit the Git commit itself (`git commit --amend`), not (just) the text on the GitHub PR. Once done, force-push it to your branch like this: `git push --force-with-lease origin patch-2`)

**Comment by rettichschnidi** [comment]
Great, thanks and welcome to the awesome Git world!

Looks much better, but has some problems which our CI, and most of the Git world, do not like:
- No empty line between subject (first line of the commit) and the body (everything after).
- The lines should not be overly long (more than 80 characters). Instead of this:
  > registration_data_t is not freed if the server does not respond to the connection message or the user decides to quit the (Wakaama) client before the server respond.
  you should do this:
  > registration_data_t is not freed if the server does not respond to the
  > connection message or the user decides to quit the (Wakaama) client before the
  > server respond.

You should be able to fix this the same way as you did before.

Meanwhile, I'll try to properly review the code changes as I promised a (too) long time ago...

**Comment by parmi93** [comment]
I edited the message as you suggested.

**Comment by rettichschnidi** [comment]
I have started reviewing the code, but I am not 100% sure yet how exactly the callback is supposed to be used. Will need a bit more time to get up to speed.

**Comment by rettichschnidi** [comment]
The line breaks are now good, but there is no subject anymore.

My suggestions:

```
Fix memory leak on client registration failure

Fix memory leak when the client fails to register with the server
registration_data_t is not freed if the server does not respond to the
connection message or the user decides to quit the (Wakaama) client before the
server respond.

This fixes #693.
```

Relevant links:
 - https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
 - https://gist.github.com/turbo/efb8d57c145e00dc38907f9526b60f17 (just a random page, there are many more on how to write proper commit messages)

**Comment by parmi93** [comment]
I fixed the subject and the body, hope it works this time

**Comment by parmi93** [comment]
Fixed the commit message according to the rules.

**Comment by parmi93** [comment]
Code formatted with `git clang-format-14`

**Comment by rettichschnidi** [comment]
Looking good. Thanks for the patience!

**Pull request merged**
