### PR TITLE
Fix for issue #237: report empty payload for Read on /ObjectID for Ob…

### PR DESCRIPTION
**Pull request by dnav**
…jects with no Instances.

Also handle Discover operation.

Signed-off-by: David Navarro <david.navarro@intel.com>

### CODE REVIEW

**Comment by dnav** [comment]
Piggybacking: align attributes reporting with the latest TS.

**Comment by fdur** [comment]
Hi,
in your updates, I think that in objects.c file, in object_read API, the following update is needed:

From
```
if (result == COAP_205_CONTENT)
    {
        if (size == 0)
        {
            *lengthP = 0;
        }
```
To
```
if (result == COAP_205_CONTENT)
    {
        if (size == 0)
        {
            *lengthP = lwm2m_data_serialize(uriP, size, dataP, formatP, bufferP);
        }
```
in order to get the right format (else format seems to remains NULL and not set to LWM2M_CONTENT_TLV or JSON)

**Comment by dnav** [comment]
Hi,

In another change already merged into master but ot in this branch, before calling object_read(), format is set to the value in the accept option or `text format` if this one is not present.
I think this solves the issue you are pointing.

Regards,

**Comment by jvermillard** [comment]
This fix doesn't work because the content format is NULL so the server can't parse the payload as a TLV

**Pull request merged**
