### PR TITLE
[GH-182] ci: Generate coverage information

### PR DESCRIPTION
**Pull request by rettichschnidi**
When reviewing this PR, please check if, after installing `gcovr`, the following line gives you a nice coverage report on your own machine:
```
tools/ci/run_ci.sh --run-tests --clean --test-coverage html
xdg-open /home/reto/code/3rd-party/wakaama/build-wakaama-tests/coverage/report.html
``` 

I am aware that this is a very simple solution and does not bring any integration with PRs. I have a solution in mind, but it requires some settings to be changed in the GitHub repository, which I can not do.

### CODE REVIEW

**Comment by rettichschnidi** [comment]
@mlasch Please review

**Comment by rettichschnidi** [comment]
FYI: You can find the artifact with the coverage information here: https://github.com/eclipse/wakaama/actions/runs/704433333 (last artifact as of writing this comment)

**Review by mlasch — APPROVED** [review]

**Comment by sbernard31** [comment]
There is maybe something wrong with code coverage. 
I get a mail with this message : **Measure coverage: All jobs have failed**
Which links to https://github.com/eclipse/wakaama/actions/runs/707729378

**Comment by mlasch** [comment]
There was a connection error during the CI run, @rettichschnidi  can you re-run the job?
```
Err:13 http://security.ubuntu.com/ubuntu focal-updates/main amd64 python3-lxml amd64 4.5.0-1ubuntu0.2
  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/lxml/python3-lxml_4.5.0-1ubuntu0.2_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
Fetched 767 kB in 0s (7917 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by sbernard31** [comment]
yep I think it's ok now : https://github.com/eclipse/wakaama/actions/runs/707729378

**Comment by rettichschnidi** [comment]
FYI: I was not able to re-run the jobs (only in the husqvarna fork). I think one would need to be a Wakaama committer to do so.

**Pull request merged**
