### PR TITLE
Check block2 option before recreating request as block2

### PR DESCRIPTION
**Pull request by tuve**
Signed-off-by: Tuve Nordius <tuve.nordius@husqvarnagroup.com>

### CODE REVIEW

**Comment by tuve** [comment]
[zephyr-wakaama.pcap.zip](https://github.com/eclipse/wakaama/files/6002743/zephyr-wakaama.pcap.zip)

**Comment by sbernard31** [comment]
(I just looked at the capture.)

Regarding https://github.com/eclipse/wakaama/issues/536#issuecomment-776052409 :  
- this fix only the infinite loop issue. 
- But there is still the "not expected 4.13" issue. Do you plan to fix it in another PR ?

**Comment by mlasch** [comment]
@sbernard31 I can verify your findings with my test setup 
```
wakaama server, block size: 128
  -> zephyr client, block size 256 (somehow ignores the setting and sends without block-wise)
  -> wakaama client, block size: 256
```
- endless loop fixed
- still sending **4.13 Request too large** and **2.31 Continue** as a response to a response

**Comment by tuve** [comment]
I missed that the response part was an issue as well. I will update this.

**Comment by tuve** [comment]
Here is the pcap, verifying that we do not respond with an error code to a response.
[zephyr-wakaama.pcap.zip](https://github.com/eclipse/wakaama/files/6009098/zephyr-wakaama.pcap.zip)

**Comment by sbernard31** [comment]
The capture sounds good now. 

I waiting for approval before to merge. :)

**Review by mlasch — APPROVED** [review]

**Comment by mlasch** [comment]
Sorry for the delay. The changes look good for me now.

**Comment by sbernard31** [comment]
Integrated in master (commit 771bf033b676d47666fd71894a979f7bfffc7728 and 04a04bffd30ba2297076ae88df23469933b10ed9)

**Pull request closed without merging**
