### PR TITLE
tinydtls: Update to most recent version, simplify usage

### PR DESCRIPTION
**Pull request by rettichschnidi**
While (again) not an official release, this will advance us by 274 commits:

```
$ git rev-list --count 178b945e5497b813b1239e2fbf57e34b7488745f..HEAD
274
```

Smoke tested like this (after registering [here](https://leshan.eclipseprojects.io/bs/) and [here](https://leshan.eclipseprojects.io/#/security)):
image

image

```
$ examples/client/lwm2mclient_tinydtls -h leshan.eclipseprojects.io -4 -p 5784 -n wakaama-560-with-dtls -i wakaama-560-with-dtls -s 5cdafa07cf5d7e0e65b8e504bc0dc9 -b
Trying to bind LWM2M Client to port 56830
LWM2M Client "wakaama-560-with-dtls" started on port 56830
>  -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
60 bytes received from [23.97.187.154]:5784
16 FE FD 00  00 00 00 00  00 00 00 00  2F 03 00 00   ............/...
23 00 00 00  00 00 00 00  23 FE FD 20  B8 4A 5F 7E   #.......#.. .J_~
96 8B F1 EF  0B ED 54 EA  06 01 7F C8  37 D2 69 D0   ......T.....7.i.
B5 BD 79 08  35 9D E9 4D  30 43 B2 9C                ..y.5..M0C..
 -> State: STATE_BOOTSTRAPPING
126 bytes received from [23.97.187.154]:5784
16 FE FD 00  00 00 00 00  00 00 01 00  58 02 00 00   ............X...
4C 00 01 00  00 00 00 00  4C FE FD 63  F8 D9 59 81   L.......L..c..Y.
2A 68 7F EC  D6 89 73 E2  42 CE D0 0C  E5 84 D1 F0   *h....s.B.......
64 A8 17 01  30 8D 51 F1  FD F4 42 20  01 FD 3D 8F   d...0.Q...B ..=.
A0 18 3F 15  78 D0 8C 2D  37 8F 2E 20  63 30 A3 68   ..?.x..-7.. c0.h
C7 B1 6B 89  24 6E DE 5B  FA 8D 08 EC  C0 A8 00 00   ..k.$n.[........
04 00 17 00  00 16 FE FD  00 00 00 00  00 00 00 02   ................
00 0C 0E 00  00 00 00 02  00 00 00 00  00 00         ..............
 -> State: STATE_BOOTSTRAPPING
67 bytes received from [23.97.187.154]:5784
14 FE FD 00  00 00 00 00  00 00 03 00  01 01 16 FE   ................
FD 00 01 00  00 00 00 00  00 00 28 00  01 00 00 00   ..........(.....
00 00 00 22  D4 1E D9 06  A6 F9 00 B5  72 A1 85 E1   ..."........r...
77 16 5D 56  CA F3 09 3F  21 48 BC E0  B4 11 C9 FF   w.]V...?!H......
71 19 B3                                             q..
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_BOOTSTRAPPING
37 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 01 00  18 00 01 00   ................
00 00 00 00  01 61 68 16  BC B7 55 C0  16 C9 19 D4   .....ah...U.....
FE 32 61 0D  96                                      .2a..
 -> State: STATE_BOOTSTRAPPING
43 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 02 00  1E 00 01 00   ................
00 00 00 00  02 B6 28 89  D1 61 A9 0E  BB 77 16 8D   ......(..a...w..
2E A6 84 82  FE 17 97 0C  DC A9 B7                   ...........
 -> State: STATE_BOOTSTRAPPING
43 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 03 00  1E 00 01 00   ................
00 00 00 00  03 E0 3A E3  8C 69 33 F8  7E 8C 47 0C   ......:..i3.~.G.
44 A2 E0 F9  00 B0 8E 59  21 52 EF                   D......Y!R.
 -> State: STATE_BOOTSTRAPPING
44 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 04 00  1F 00 01 00   ................
00 00 00 00  04 53 61 C6  CC 4E 57 E7  16 92 74 F2   .....Sa..NW...t.
7C D2 57 DC  2E 72 DE F5  9D EF 22 AD                |.W..r....".
 -> State: STATE_BOOTSTRAPPING
380 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 05 01  6F 00 01 00   ............o...
00 00 00 00  05 8A 55 89  00 03 1B 4B  24 8C 94 15   ......U....K$...
AF FC BD EC  81 73 A0 89  EC 55 E3 05  03 EF BC D0   .....s...U......
E8 2F ED A6  30 41 76 E4  59 84 AF A9  38 67 3A 71   ./..0Av.Y...8g:q
0F 89 57 1A  6B 3A 22 73  C3 A2 FC 4F  6A DD D4 21   ..W.k:"s...Oj..!
D4 3A E6 2C  EC 4B EA D3  5F 2C EC 2A  E9 2A 80 93   .:.,.K.._,.*.*..
CD 9D 0B 6E  47 FE 01 12  F9 BC CE A4  88 49 40 AB   ...nG........I@.
D5 BF 6D 80  E7 D4 0A 0D  C0 1B 6C 5E  57 29 69 AC   ..m.......l^W)i.
04 5F 36 D0  F9 91 4A 5B  4E F2 13 E1  4A 85 62 76   ._6...J[N...J.bv
5E 46 21 FE  3D 1C 00 56  DB 1F BA C4  23 D9 3B 0E   ^F!.=..V....#.;.
41 41 A2 3D  46 00 78 70  EE 87 33 83  24 9C EA 51   AA.=F.xp..3.$..Q
E0 A9 36 AE  42 15 37 66  50 92 79 76  E0 AD B2 96   ..6.B.7fP.yv....
ED 83 3E D5  6D E7 BB 1F  30 CF C0 AB  92 E5 AA 98   ..>.m...0.......
17 2B 67 88  F9 9F EB E8  16 90 86 78  75 57 3E C9   .+g........xuW>.
2D 8E 6D 7B  30 5F 11 C5  7F EF 97 7B  C2 87 0C 46   -.m{0_.....{...F
83 38 FA 1F  3F 5A B6 2A  3B 49 05 64  06 65 09 63   .8..?Z.*;I.d.e.c
34 28 0C D9  37 22 DC 85  BB A4 A5 D2  2A DE 7D 11   4(..7"......*.}.
D0 1A 08 F2  F3 97 8F 2C  E0 DF 27 E1  AC 11 C4 C5   .......,..'.....
06 1F 8F C4  A7 34 D7 37  D8 C8 2D 98  E1 F4 09 E0   .....4.7..-.....
A4 81 6A C3  F3 09 07 72  4F 5A D9 76  98 07 42 B5   ..j....rOZ.v..B.
05 F6 FF 62  6C 0E FF 67  52 2E 76 62  E3 15 AC 5B   ...bl..gR.vb...[
AC 2A 19 1E  73 71 94 5C  80 AF 03 C3  23 FE 11 26   .*..sq.\....#..&
DA 08 A5 38  E1 F9 DD 1B  50 0B 41 0E  1B 28 B2 3D   ...8....P.A..(.=
63 06 E0 6C  A2 B5 4A A0  93 6A C6 FD                c..l..J..j..
 -> State: STATE_BOOTSTRAPPING
153 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 06 00  8C 00 01 00   ................
00 00 00 00  06 CB 16 9E  6A 1C AB D0  5C 52 F1 8C   ........j...\R..
8A 23 06 FF  67 04 61 2C  1A B2 56 3D  CE 56 D2 41   .#..g.a,..V=.V.A
27 22 86 DB  69 6F A2 5C  1F 71 CC 30  C0 C4 C4 8F   '"..io.\.q.0....
E9 E1 55 1C  C9 4E 28 F6  09 59 85 6E  4C BE 0E 8C   ..U..N(..Y.nL...
96 1A B1 A6  19 01 DE 6A  82 71 C0 86  9D D0 DD 55   .......j.q.....U
71 58 2B 78  C9 3C 3E 10  82 EA BC F3  99 C0 E0 FE   qX+x.<>.........
7B AF 01 68  05 F3 12 16  D6 5A 7F A1  63 47 5E 5C   {..h.....Z..cG^\
05 D6 BF 95  32 48 B9 F9  32 8A E7 EE  00 E2 CE 03   ....2H..2.......
29 17 D4 A9  15 07 7D 02  F9                         ).....}..
 -> State: STATE_BOOTSTRAPPING
44 bytes received from [23.97.187.154]:5784
17 FE FD 00  01 00 00 00  00 00 07 00  1F 00 01 00   ................
00 00 00 00  07 26 A3 E5  DD 5B 47 E6  E9 44 92 D4   .....&...[G..D..
3B 2C EA 2A  DC D0 18 02  EE 2F 2D C9                ;,.*...../-.
 -> State: STATE_BOOTSTRAPPING
 -> State: STATE_REGISTERING
60 bytes received from [23.97.187.154]:5684
16 FE FD 00  00 00 00 00  00 00 00 00  2F 03 00 00   ............/...
23 00 00 00  00 00 00 00  23 FE FD 20  E9 19 40 0E   #.......#.. ..@.
A4 3E D3 28  8B A7 63 C6  64 29 9D 3E  93 37 55 8D   .>.(..c.d).>.7U.
92 D3 FF 7E  6B F9 EE 71  8F EB C8 66                ...~k..q...f
 -> State: STATE_REGISTERING
126 bytes received from [23.97.187.154]:5684
16 FE FD 00  00 00 00 00  00 00 01 00  58 02 00 00   ............X...
4C 00 01 00  00 00 00 00  4C FE FD 63  F8 D9 5B 91   L.......L..c..[.
06 A8 D0 48  28 F3 7A AA  35 D0 D0 E0  A8 7A 04 11   ...H(.z.5....z..
B9 CB 3C EE  66 D9 1E 3E  C0 2E 0F 20  BF F2 43 B2   ..<.f..>... ..C.
CE BA 28 27  17 2E 0D C3  D2 3D AB A9  1E 96 8F 8C   ..('.....=......
82 2B A6 A3  5B 51 40 C1  78 39 92 6F  C0 A8 00 00   .+..[Q@.x9.o....
04 00 17 00  00 16 FE FD  00 00 00 00  00 00 00 02   ................
00 0C 0E 00  00 00 00 02  00 00 00 00  00 00         ..............
 -> State: STATE_REGISTERING
67 bytes received from [23.97.187.154]:5684
14 FE FD 00  00 00 00 00  00 00 03 00  01 01 16 FE   ................
FD 00 01 00  00 00 00 00  00 00 28 00  01 00 00 00   ..........(.....
00 00 00 23  75 19 AF A5  11 93 A2 EB  6B DB CC E6   ...#u.......k...
B6 B0 4E 10  83 BA 0C 46  B3 48 8C 7A  32 F0 D9 AA   ..N....F.H.z2...
2A B1 34                                             *.4
 -> State: STATE_REGISTERING
 -> State: STATE_REGISTERING
51 bytes received from [23.97.187.154]:5684
17 FE FD 00  01 00 00 00  00 00 01 00  26 00 01 00   ............&...
00 00 00 00  01 47 5C D6  1B 6F 16 55  0A 93 9C F6   .....G\..o.U....
4E 00 A9 BE  8F CC 62 B6  64 15 C4 28  63 47 49 B1   N.....b.d..(cGI.
2A BC CD                                             *..
 -> State: STATE_READY
quit

non IPV4 or IPV6 address
non IPV4 or IPV6 address
non IPV4 or IPV6 address
non IPV4 or IPV6 address
```

### CODE REVIEW

**Comment by tuve** [comment]
Do we need a new CQ for this, the existing one is for version 0.8.2

**Comment by sbernard31** [comment]
> Do we need a new CQ for this, the existing one is for version 0.8.2

You are talking about **tinydtls** dependency right ? 

As now [**tinydtls** is an eclipse project](https://projects.eclipse.org/projects/iot.tinydtls), AFAIK no CQ is needed. 

You could ask why does it exist a CQ for the version 0.8.2 ? 
Good question, I guess probably before tinydtls become an eclipse project :thinking:

**Comment by boaks** [comment]
Just to mention:
tinyDtls made a lot of progress and is still making progress.
If you're interested, for testing the "develop" branch contains many bugfixes of the last months and there are still improvement and bugfixes pending. So I would recommend, to check frequently, if that works for you.

**Comment by sbernard31** [comment]
@boaks do you know the idea behind `master` and `develop` branch ? I'm not sure to get the development process ? 
(or maybe @obgm could answer about it ?)
Let me know if I should rather ask this at https://github.com/eclipse/tinydtls/issues)

**Comment by boaks** [comment]
I don't know. So asking @obgm is the best.

**Comment by obgm** [comment]
The reason for these branches is that it follows the usual best practices for git workflows with a stable main branch, and a develop branch where the next stable version is being prepared.
The odd thing for tinydtls is that there is not really a stable version as it has never been released while under the hood of Eclipse Foundation; The current main branch reflects the initial contribution and will be updated once the 1.0 release process has finished.

**Comment by obgm** [comment]
Thanks to @boaks I think we are getting closer to this initial release within the next weeks.

**Comment by rettichschnidi** [comment]
> Thanks to @boaks I think we are getting closer to this initial release within the next weeks.

Would you (tinydtls) prefer Wakaama to update now (and again in a few weeks) or wait for the final release?

**Comment by tuve** [comment]
+1 for the final release

**Comment by boaks** [comment]
> Would you (tinydtls) prefer Wakaama to update now (and again in a few weeks) or wait for the final release?

That depends on what you want. I usually try the "newest", but with care, mainly in order to find left or new bugs.
FMPOV, the current "develop" is worth to be used, even if some issues are open.
I guess, in some weeks, it will be worth again to update. 
Don't forget to report issues, if you get faced ones.

**Comment by obgm** [comment]
I suppose updating now is a good idea, especially as the release process will take some time. We could provide a new release candidate soon if you prefer to have some synchronization point.

**Comment by sbernard31** [comment]
@obgm, I think I get it, you're master branch is a kind of maintenance branch. 

Currently tinydtls is just used for example / demo, right ?
IMHO a Wakaama release should ideally use a released version of tinydtls but during development phase, this could OK to use a development branch. (especially if this is just for demo)

E.g. Leshan (LWM2M in java) development branch (`master`) frequently depends on development version of Scandium (DTLS in java). It allows to provide feedback or detect bugs sooner. The only constraint is that you need to ensure that the library you depend on will release in an acceptable time for you.

**Comment by rettichschnidi** [comment]
> Currently tinydtls is just used for example / demo, right ? 

Yes, its works-with.

side note: I intend to include the DTLS enabled client binary in the integration testing, but even then, it will not be a dependency of the Wakaama library itself.

**Comment by rettichschnidi** [comment]
Just updated this PR on the most recent Wakaama master and with the most recent commit of tindydtls (there is no release yet). Suggesting to merge this PR in this current state.

**Comment by boaks** [comment]
I consider, that when the  PR for RFC5746 is merged into tinydtls/main, a update would make again sense.
I will ping, when we merged it.

**Comment by rettichschnidi** [comment]
Just realized the thumbs up from @boaks. I consider this an approval and therefore merge this PR. :dancers:

**Pull request merged**
