### PR TITLE
Add integration tests int-201, int-204 (requires PR#598, PR#602)

### PR DESCRIPTION
**Pull request by qleisan**
Add integration tests that use plain-text and JSON

### CODE REVIEW

**Comment by rettichschnidi** [comment]
This is hard to review - would rather see this merged into #598.

**Comment by qleisan** [comment]
I just split #598 to reduce the number of dependencies to get this first integration test PR merged to master

**Comment by rettichschnidi** [comment]
I do not thing this is the right approach - I'd rather have #598 massaged really well - just one (or very few tests), but including CI integration, before adding many PRs which depend on #598.

**Comment by qleisan** [comment]
Reorganizing - will create a new PR with this and other content

**Pull request closed without merging**
