### PR TITLE
license: Rename license for Github to detect it

### PR DESCRIPTION
**Pull request by mlasch**
Rename license for Github to detect it, similar to Leshan. #491

### CODE REVIEW

**Comment by sbernard31** [comment]
I'm not sure it works to use `EDL-1` suffix :thinking:,  did you check on your personal forked repository ?

It works if you can see : BSD-3-Clause, EPL-2.0 licenses found  on the right of the github home page under tags.
Like in Leshan : https://github.com/eclipse-leshan/leshan

Note that EDL-1 license is exactly a BSD-3-Clause. (Leshan is also licensed under epl 2 and edl 1)
Why edl-1 is not supported ? I asked about it long time ago : https://lists.spdx.org/g/Spdx-legal/topic/22080928#2105
So it's expected that GitHub see edl1 as BSD-3 license.

**Comment by mlasch** [comment]
> I'm not sure it works to use EDL-1 suffix 🤔, did you check on your personal forked repository ?

The licenses will show up in Github as "Unknown, EPL-2.0 licenses found ". At least the EDL-1 is recognized as a license file, even though unknown. 

> Note that EDL-1 license is exactly a BSD-3-Clause.

Not sure I understand you correctly. Can we just replace EDL-1 with BSD-3 in Wakaama (same as with Leshan), or should we keep EDL-1 and accept that Github does not show it correctly? Both would be fine for me.

**Comment by sbernard31** [comment]
> Not sure I understand you correctly. Can we just replace EDL-1 with BSD-3 in Wakaama 

I think you can replace EDL-1 with BSD-3. 
@waynebeaton could you confirm that it's OK to replace `EDL-1` suffix by `BSD-3` suffix and so github is able to show `BSD-3-Clause` instance of `Unknown` ?

**Comment by boaks** [comment]
> I think you can replace EDL-1 with BSD-3.

At least that was the advice for Californium.

**Review by sbernard31 — APPROVED** [review]

**Comment by waynebeaton** [comment]
Yes. In fact, the [documentation generator](https://www.eclipse.org/projects/tools/documentation.php?id=iot.wakaama#copyright) recommends exactly this.

Use `BSD-3-Clause`  if you can. While there's all kinds of standards, I find that there is a strong preference to using the SPDX code for the name of the file with an extension that describes the format, e.g., `BSD-3-Clause.md` or similar. This is not a requirement... just an observation.

FWIW, the BSD licenses are referred to as "template" licenses. When you use them, you change certain parts of the text, but they're basically still just the BSD license. So the EDL is just our appliaction of the BSD. From a license management perspective, it's way easier for everybody if we treat all of the various applications of the BSD uniformly.

**Pull request merged**
