### PR TITLE
Bootstrap Delete /0 keep bootstrap server account

### LINKED ISSUE #445: Bootstrap-Delete incorrectly deletes the Security object for the bootstrap server
The LWM2M spec states:

> Only in Bootstrap Interface, the Delete operation MAY targets “/0” URI. In that case, the operation MUST delete all the existing Security Object Instances - **except LwM2M Bootstrap-Server Account** - in the LwM2M Client;

and:

> if no Object ID is indicated, all existing Object Instances (**except the LwM2M Bootstrap-Server Account one**) in the LwM2M Client will be deleted.

The boostrap Security object should only be deleted if that instance is specifically deleted.

### PR DESCRIPTION
**Pull request by sbertin-telular**
The LWM2M spec states:
Only in Bootstrap Interface, the Delete operation MAY targets “/0” URI.
In that case, the operation MUST delete all the existing Security
Object Instances - except LwM2M Bootstrap-Server Account - in the LwM2M
Client;

This changes the logic for the Delete /0 case to match the Delete All.
It avoids deleting the Security object for the bootstrap server.

Fixes #445.

Signed-off-by: Scott Bertin <sbertin@telular.com>

### CODE REVIEW

**Comment by sbertin-telular** [comment]
Rebased. After today I'll be away until November 30.

**Comment by sbertin-telular** [comment]
@rettichschnidi, @qleisan, or @tuve please review.

**Comment by qleisan** [comment]
I'll do it on monday!

**Comment by qleisan** [comment]
It "looks ok", but I'd like do some practical tests with bootstrapping and read up on the spec to feel confident about the logic (here and the "bigger picture"). That will will require some investment in time. 
No objections if you want to go ahead and merge.

**Comment by sbernard31** [comment]
@qleisan,  I will wait until 30 november (when @sbertin-telular  will be back), this way that give you some more days.

If 30 november you don't succeed to do what you want. I merge it  anyway.
If you find issue after merge we will fix it in another PR.

Does it sounds good ?

**Comment by qleisan** [comment]
Absolutely!

**Comment by sbernard31** [comment]
Integrated in master (commit 3b55c8f349e1049f5223e450eab47506744ece15)

**Pull request closed without merging**
